version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: plugin_user
      POSTGRES_PASSWORD: plugin_password
      POSTGRES_DB: plugin_db
    ports:
      - "${POSTGRES_PORT:-5434}:5432" # Changed host port mapping to 5433 to avoid conflict
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # Redis service for Socket.IO adapter
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 
  redis_data: 